# Generated by Django 2.2 on 2021-02-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSF_Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('credited_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='TSF_Bank.Customer')),
                ('debited_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='TSF_Bank.Customer')),
            ],
        ),
    ]
